let pieces = {

    0: {title: "The Breakfast Club", author: "JGS", art: "no", content: "./pieces/0.txt"},
    1: {title: "A Prediciton Made on 2/20/20", author: "JGS", art: "./art/1.JPG", content: "./pieces/1.txt"},
    2: {title: "My Father", author: "JGS", art: "no", content: "./pieces/2.txt"},
    3: {title: "The Five to Sleep Over", author: "VIN", art: "no", content: "./pieces/3.txt"},
    4: {title: "Varsity", author: "", art: "no", content: "./pieces/4.txt"},
    5: {title: "Family Matters", author: "NISH", art: "no", content: "./pieces/5.txt"},
    6: {title: "Problems", author: "GYS", art: "./art/6.jpg", content: "./pieces/6.txt"},
    7: {title: "Miami Nights", author: "MMM", art: "./art/7.jpg", content: "./pieces/7.txt"},
    8: {title: "COVID", author: "ME", art: "./art/8.png", content: "./pieces/8.txt"},
    9: {title: "Snoop Dogg", author: "JGS/SHK", art: "no", content: "./pieces/9.txt"},
    10: {title: "Middle America", author: "EBC", art: "no", content: "./pieces/10.txt"},
    11: {title: "Amputee", author: "AMP", art: "no", content: "./pieces/11.txt"},
    12: {title: "Water Boy", author: "VIN", art: "no", content: "./pieces/12.txt"},
    13: {title: "The Princess Diaries", author: "VIN", art: "no", content: "./pieces/13.txt"},
    14: {title: "Sending A Message", author: "GPL", art: "no", content: "./pieces/14.txt"},
    15: {title: "Squid vs. the Sharks", author: "ZDG", art: "./art/15.PNG", content: "./pieces/15.txt"},
    16: {title: "Asimov's First Law of Robotics", author: "GPL", art: "no", content: "./pieces/16.txt"},
    17: {title: "Big Sam", author: "ASL", art: "no", content: "./pieces/17.txt"},
    18: {title: "Damp Rag", author: "JGS", art: "no", content: "./pieces/18.txt"},
    19: {title: "Letter to the U.S. President", author: "JGS", art: "./art/19.PNG", content: "./pieces/19.txt"},
    20: {title: "The Ice Cream Man", author: "VIN", art: "no", content: "./pieces/20.txt"},
    21: {title: "Shmeeps", author: "BLW", art: "no", content: "./pieces/21.txt"},
    22: {title: "There's No 'I' in Clone", author: "VIN", art: "no", content: "./pieces/22.txt"},
    23: {title: "Pen Is", author: "DJL", art: "no", content: "./pieces/23.txt"},
    24: {title: "Just Another Happy Human", author: "YMC", art: "no", content: "./pieces/24.txt"},
    25: {title: "Existential Musings", author: "VIN", art: "no", content: "./pieces/25.txt"},
    26: {title: "Morbid", author: "ME", art: "no", content: "./pieces/26.txt"},
    27: {title: "Spoils of War", author: "VIN", art: "no", content: "./pieces/27.txt"},
    28: {title: "Neighbors", author: "JPW", art: "no", content: "./pieces/28.txt"},
    29: {title: "The Ministry of Tasty Treats", author: "VIN", art: "no", content: "./pieces/29.txt"},
    30: {title: "Setting the Record Straight", author: "JGS", art: "no", content: "./pieces/30.txt"},
    31: {title: "Jungle", author: "JLN", art: "no", content: "./pieces/31.txt"},
    32: {title: "The Penis", author: "JGS", art: "no", content: "./pieces/32.txt"},
    33: {title: "Australia Australia Australia Australia Australia Australia Australia Australia Australia Australia", author: "JFAR", art: "no", content: "./pieces/33.txt"},
    34: {title: "THE LAMPOON AI#", author: "BJF", art: "./art/34.png", content: "no"}



}
